feat:redux, api
IvanDavydenkov/react-burger pull request #2
Opened 2024-12-02 22:48 UTC by IvanDavydenkov

2024-12-03 07:27 UTC, kyzinatra commented on src/components/pages/home/ui/burger-ingredient/burger-ingredient.tsx
>  	return (
Надо исправить: по заданию весь список ингредиентов должен быть доступен сразу. Клики по табам могут проскроливать до нужного места

2024-12-03 07:28 UTC, kyzinatra commented on src/components/pages/home/ui/burger-ingredients/burger-ingredients.tsx
>  			</Modal>
Отлично! Хорошая реализация модального окна. Круто, что вы сделали анимацию

2024-12-03 07:31 UTC, kyzinatra requested changes
Отличная работа! Понравилась как организована верстка! Хорошая декомпозиция компонентов, круто, что вы сделали анимацию у модальных окон. Стоит поправить только список ингредиентов в соответствии с заданием и ваша работа будет принята!

2024-12-03 18:59 UTC, IvanDavydenkov commented on src/components/pages/home/ui/burger-ingredient/burger-ingredient.tsx
>  	return (
Сделал, но при скролле плохая чувствительность на изменение таба. Если в будущем добавится кол-во продуктов - будет ок) А пока снизу вверх работает лучше, чем сверху вниз)

2024-12-04 12:51 UTC, kyzinatra approved these changes
Вы отлично потрудились.
Поздравляю! Ваша работа принята.
Удачного дальнейшего обучения.

2024-12-04 13:20 UTC, merged